/**
 * Vendor the three YARG faces as woff2, so the popover renders in them offline.
 *
 * The web client pulls Red Hat Display, Barlow and Inter from
 * `fonts.googleapis.com` at runtime and its own comment calls self-hosting "the
 * remaining fix". For a desktop app on a machine about to host a party — quite
 * possibly with the router busy or the internet off — it is not a remaining
 * fix, it is the difference between the design system and Segoe UI. Measured
 * before this existed: the declared display stack rendered byte-identically to
 * `system-ui`, so every uppercase label in the window was Segoe.
 *
 * Run this by hand when a weight is added; the output is committed. Google's
 * CSS API is asked as a modern browser so it answers with woff2, and only the
 * `latin` and `latin-ext` subsets are kept — this window shows English UI text
 * and Windows paths, and the Cyrillic, Greek and Vietnamese cuts are dead
 * weight inside an asar.
 *
 *     node desktop/scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'ui', 'fonts')

/** Only the weights the popover actually renders. Adding one means adding it here. */
const FACES = [
  { family: 'Red Hat Display', weight: 800, slug: 'red-hat-display' },
  { family: 'Barlow', weight: 400, slug: 'barlow' },
  { family: 'Inter', weight: 400, slug: 'inter' },
]

const SUBSETS = new Set(['latin', 'latin-ext'])

// Anything older and the API answers with ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'

async function fetchText(url) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`)
  return response.text()
}

await mkdir(OUT, { recursive: true })

const blocks = []

for (const face of FACES) {
  const spec = `${face.family.replace(/ /g, '+')}:wght@${face.weight}`
  const css = await fetchText(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`)

  // Each `@font-face` is preceded by a `/* subset */` comment naming it.
  const chunks = css.split('/*').slice(1)

  for (const chunk of chunks) {
    const subset = chunk.slice(0, chunk.indexOf('*/')).trim()
    if (!SUBSETS.has(subset)) continue

    const src = /src: url\((https:[^)]+\.woff2)\)/.exec(chunk)?.[1]
    const range = /unicode-range: ([^;]+);/.exec(chunk)?.[1]
    if (!src || !range) throw new Error(`could not read the ${subset} block for ${face.family}`)

    const name = `${face.slug}-${face.weight}-${subset}.woff2`
    const body = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer())
    await writeFile(join(OUT, name), body)
    console.log(`[fonts] ${name}  ${(body.length / 1024).toFixed(1)} KB`)

    blocks.push(
      [
        '@font-face {',
        `  font-family: '${face.family}';`,
        '  font-style: normal;',
        `  font-weight: ${face.weight};`,
        // `block` and not `swap`: the file is local and resolves in a frame or
        // two, and a popover that repaints its own labels after opening looks
        // broken in a way a web page does not.
        '  font-display: block;',
        `  src: url('./${name}') format('woff2');`,
        `  unicode-range: ${range};`,
        '}',
      ].join('\n'),
    )
  }
}

const header = `/*
 * Generated by desktop/scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Red Hat Display, Barlow and Inter, all three under the SIL Open Font
 * License 1.1, subset to latin and latin-ext. These are the faces the YARG
 * design system names in \`typography.css\`; vendoring them is what keeps this
 * window from rendering in the platform sans with the network down.
 */
`

await writeFile(join(OUT, 'fonts.css'), `${header}\n${blocks.join('\n\n')}\n`)
console.log(`[fonts] wrote fonts.css with ${blocks.length} faces`)
